### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by hbadi** [qarnot/qarnot-sdk-csharp#1]
Hi

Is there any c# example ?
I compiled the Qarnot SDK and wrote a sample test that does not work when using Async methods  (i don't see any task created in the dashboard), it works with pedrecated methods .Run

            var connect = new QarnotSDK.Connection(MyToken);
            var task1 = connect.CreateTask("TestFromDotNet", "docker-batch", 1);
            task1.Constants.Add("DOCKER_CMD", "Hello : ${INSTANCE_ID}");
            task1.RunAsync();
            System.Console.WriteLine(task1.StdoutAsync());

Best regards.

**Comment by gnebie** [comment]
Hello, 

Yes, in your example you don't wait for the async tasks you started so your program end before completing them. 
You can use Wait and Result in your program or use (and wait for) an async function to launch them and wait for them (this is the best practice)  
Also the docker command is a shell command so "Hello : ${INSTANCE_ID}" will not work since "Hello" is not a classic binary or shell command. you need to specify a command to be execute, "echo Hello : ${INSTANCE_ID}" will print an `Hello : 0` in the stdout 

A full example of the 2 methods : 
```C#
using System;
using QarnotSDK;
using System.Threading;
using System.Threading.Tasks;

namespace testQarnot
{
    class Program
    {
        public static void TestQarnotSync(string MyToken)
        {
            var connect = new QarnotSDK.Connection(MyToken);
            var task1 = connect.CreateTask("TestFromDotNetSync", "docker-batch", 1);
            task1.Constants.Add("DOCKER_CMD", "echo Hello : ${INSTANCE_ID}");
            task1.RunAsync().Wait();
            System.Console.WriteLine(task1.StdoutAsync().Result);
        }

        public static async Task TestQarnotAsync(string MyToken)
        {
            var connect = new QarnotSDK.Connection(MyToken);
            var task1 = connect.CreateTask("TestFromDotNetAsync", "docker-batch", 1);
            task1.Constants.Add("DOCKER_CMD", "echo Hello : ${INSTANCE_ID}");
            await task1.RunAsync();
            System.Console.WriteLine(await task1.StdoutAsync());
        }

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            var token = "";
            TestQarnotSync(token);
            TestQarnotAsync(token).Wait();
            Console.WriteLine("After the run!");
        }
    }
}
```

You can also find the SDK C# documentation here: 
https://computing.qarnot.com/documentation/sdk-csharp/

The global Qarnot documentation here : 
https://computing.qarnot.com/en/developers/overview/qarnot-computing-home

And some more examples here: 
https://blog.qarnot.com/

Best regards.
